# Generated by Django 6.0 on 2025-12-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='featured_foods/')),
                ('ingredients', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
