# Generated by Django 6.0 on 2026-01-02 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
