# Generated by Django 6.0 on 2026-01-03 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_is_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedFood',
        ),
    ]
